# Build
#docker build --network=host --rm -t mariadb:1.0.0 --file /home/juetxeba/inception/srcs/requirements/mariadb/Dockerfile ./

# Check Docker images on your Linux machine
#docker image list --all

name: inception

services:
  mariadb:
    build: ./requirements/mariadb
    env_file: ../secrets/.env
    environment:
      SECRET: /run/secrets/mariadb-secrets
    secrets:
      - db_name
      - db_password
      - db_user
      - db_r_password
    container_name: mariadb
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      - db-net
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  nginx:
    build:
      context:  ./requirements/nginx
    container_name: nginx
    env_file: ../secrets/.env
    secrets:
       - key.pem
       - cert.pem
    depends_on:
      wordpress:
        condition: service_healthy
    expose:
      - "443"
    ports:
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "pidof nginx || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
      start_interval: 5s
    domainname: juetxeba.42.fr
    networks:
      - wp-net
    volumes:
      - website-data:/var/www/html:ro
    restart: unless-stopped

  wordpress:
    env_file: ../secrets/.env
    secrets: 
      - db_name
      - db_password
      - db_user
      - db_r_password
      - wp_admin_email
      - wp_admin_password
      - wp_admin_user
      - wp_user
      - wp_user_email
      - wp_user_password

    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm82 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      - db-net
      - wp-net
    volumes:
      - website-data:/var/www/html
    restart: unless-stopped


secrets:
  cert.pem:
    file: ../secrets/cert.pem
  key.pem:
    file: ../secrets/key.pem
  db_name:
    file: ../secrets/db_name
  db_password:
    file: ../secrets/db_password
  db_r_password:
    file: ../secrets/db_r_password
  db_user:
    file: ../secrets/db_user
  wp_admin_email:
    file: ../secrets/wp_admin_email
  wp_admin_password:
    file: ../secrets/wp_admin_password
  wp_admin_user:
    file: ../secrets/wp_admin_user
  wp_user:
    file: ../secrets/wp_user
  wp_user_email:
    file: ../secrets/wp_user_email
  wp_user_password:
    file: ../secrets/wp_user_password


volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/juetxeba/data/mariadb-volume
  website-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/juetxeba/data/wordpress-volume
networks:
  db-net:
    driver: bridge
    name: db-net
  
  wp-net:
    driver: bridge
    name: wp-net
